### ISSUE TITLE
plugin failed to register with xo-server 5.5.2

### ISSUE THREAD

**Issue by tbe** [vatesfr/xo-server-auth-ldap#25]
The plugin failes to register with
```
  xo:plugin successfully register auth-ldap +10ms
register plugin auth-ldap: XoError: invalid parameters
    at factory (/usr/share/xo/xo-server/node_modules/xo-common/src/api-errors.js:21:26)
    at _default._callee5$ (/usr/share/xo/xo-server/dist/xo-mixins/xo-mixins/plugins.js:154:30)
    at tryCatch (/usr/share/xo/xo-server/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (/usr/share/xo/xo-server/node_modules/regenerator-runtime/runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/share/xo/xo-server/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (/usr/share/xo/xo-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/share/xo/xo-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (/usr/share/xo/xo-server/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:191:7)
    at _default.<anonymous> (/usr/share/xo/xo-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at _default._configurePlugin (/usr/share/xo/xo-server/dist/xo-mixins/plugins.js:333:22)
    at /usr/share/xo/xo-server/dist/xo-mixins/xo-mixins/plugins.js:94:22
    at run (/usr/share/xo/xo-server/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:87:22)
    at /usr/share/xo/xo-server/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28
    at flush (/usr/share/xo/xo-server/node_modules/babel-runtime/node_modules/core-js/library/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by julien-f** [comment]
The plugin registered successfully (“*xo:plugin successfully register auth-ldap*”), but failed to the configuration is incorrect so the plugin could not be enabled, it usually happens because you have not yet configured it :)

**Comment by tbe** [comment]
We have used this plugin since a few weeks, but after a fresh installation we was not able to configure the plugin, neither via web-interface or configuration.

Configuration:
```
plugins:
  auth-ldap:
    uri: "ldaps://ldap.intern.piratenpartei.de"
    checkCertificate: false
    base: 'ou=people,ou=it,dc=piratenpartei,dc=de'
```

In the webinterface the plugin configuration is disabled and the is a strange error if we try to enable it. 

I can reproduce this issue on multiple systems. 
Web Interface:
![image](https://cloud.githubusercontent.com/assets/102155/21587780/5a38b2bc-d0e0-11e6-8311-671a4d48db3b.png)
![image](https://cloud.githubusercontent.com/assets/102155/21587784/69f0b47a-d0e0-11e6-856e-df08e75b9442.png)

**Comment by julien-f** [comment]
Ok, I'm taking a look!

**Comment by julien-f** [comment]
Hmm, I think I understand the issue (it took me some time to see, sorry ^^), the configuration is no longer taken from the configuration file, you should reenter the configuration directly in the web interface :)
