### ISSUE TITLE
Error while enable the ldap auth

### ISSUE THREAD

**Issue by sjkeerthi** [vatesfr/xo-server-auth-ldap#3]
I downloaded the xo-server-auth-ldap and issued the npm installed

#npm install xo-server-auth-ldap
npm WARN package.json coffeelint-no-implicit-returns@0.0.4 No repository field.
npm WARN cannot run in wd xo-server-auth-ldap@0.2.0 npm build (wd=/opt/xo-server/xo-server-auth-ldap)
 
> dtrace-provider@0.2.8 install /opt/xo-server/node_modules/xo-server-auth-ldap/node_modules/ldapjs/node_modules/dtrace-provider
> node-gyp rebuild

make: Entering directory '/opt/xo-server/node_modules/xo-server-auth-ldap/node_modules/ldapjs/node_modules/dtrace-provider/build'
  TOUCH Release/obj.target/DTraceProviderStub.stamp
make: Leaving directory '/opt/xo-server/node_modules/xo-server-auth-ldap/node_modules/ldapjs/node_modules/dtrace-provider/build'
xo-server-auth-ldap@0.2.0 node_modules/xo-server-auth-ldap
└── ldapjs@0.7.1 (assert-plus@0.1.5, asn1@0.2.1, dtrace-provider@0.2.8, nopt@2.1.1, bunyan@0.22.1, pooling@0.4.6)
[root@localhost xo-server]# cd node_modules/

After I complied I added the config.yaml and started the xo-server I could see the plugin is not avaliable.

./xo-server 
  xo:main Configuration loaded. +0ms
  xo:main Web server listening on http://[::]:80 +7ms
  xo:plugin loading auth-ldap +13ms
✖ Cannot find module 'auth-ldap'
Error: Cannot find module 'auth-ldap'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.require.resolve (module.js:388:19)
    at $XO.<anonymous> (/source/index.js:95:7)
From previous event:
    at /opt/xo-server/node_modules/lodash.map/node_modules/lodash._basecallback/node_modules/lodash._bindcallback/index.js:32:19
    at /opt/xo-server/node_modules/lodash.map/index.js:27:17
    at /opt/xo-server/node_modules/lodash.map/node_modules/lodash._baseeach/index.js:97:11
    at baseForOwn (/opt/xo-server/node_modules/lodash.map/node_modules/lodash._baseeach/index.js:52:10)
    at /opt/xo-server/node_modules/lodash.map/node_modules/lodash._baseeach/index.js:67:14
    at baseMap (/opt/xo-server/node_modules/lodash.map/index.js:26:3)
    at map (/opt/xo-server/node_modules/lodash.map/index.js:91:10)
    at loadPlugins (/source/index.js:104:17)
    at callee$0$2$ (/source/index.js:395:19)
    at tryCatch (/opt/xo-server/node_modules/babel-runtime/regenerator/runtime.js:56:40)
    at GeneratorFunctionPrototype.invoke (/opt/xo-server/node_modules/babel-runtime/regenerator/runtime.js:201:22)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
From previous event:
    at execPromise (/opt/xo-server/node_modules/exec-promise/index.js:59:22)
    at Object.<anonymous> (/opt/xo-server/bin/xo-server:7:24)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

Kindly let me know if I missing anything here

**Comment by sjkeerthi** [comment]
I tried even 

cd /xo-server/node_modules
> git clone https://github.com/vatesfr/xo-server-auth-ldap.git
> cd xo-server-auth-ldap
> npm install
> npm run build

**Comment by sjkeerthi** [comment]
closing this issue.

I resolved this issue by deleting the xo-server-auth-ldap and check out under the /opt/xo-server/node_modules/

cd /opt/xo-server/node_modules/xo-server-auth-ldap

npm install npm run build

./xo-server 
  xo:main Configuration loaded. +0ms
  xo:main Web server listening on http://[::]:80 +7ms
  xo:plugin loading auth-ldap +12ms
  xo:plugin all plugins loaded +93ms
  xo:main Setting up / → /opt/xo-server/xo-web/dist +49ms
